/* soapStub.h
   Generated by gSOAP 2.8.111 for .\Service1.asmx.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <vector>
#define SOAP_NAMESPACE_OF_tfzw	"http://Fantasy/WebServiceDemo/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208111
# error "GSOAP VERSION 208111 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

struct tfzw__AddNumbersResponse;	/* .\Service1.asmx.h:355 */
struct tfzw__AddNumbers;	/* .\Service1.asmx.h:355 */
struct tfzw__clearLinkResponse;	/* .\Service1.asmx.h:425 */
struct tfzw__clearLink;	/* .\Service1.asmx.h:425 */
struct tfzw__showExistLinkResponse;	/* .\Service1.asmx.h:492 */
struct tfzw__showExistLink;	/* .\Service1.asmx.h:492 */
struct tfzw__TestLinkSqlserverResponse;	/* .\Service1.asmx.h:562 */
struct tfzw__TestLinkSqlserver;	/* .\Service1.asmx.h:562 */
struct tfzw__executeSqlResponse;	/* .\Service1.asmx.h:635 */
struct tfzw__executeSql;	/* .\Service1.asmx.h:635 */
struct tfzw__executeSql_USCOREbackEncordResponse;	/* .\Service1.asmx.h:708 */
struct tfzw__executeSql_USCOREbackEncord;	/* .\Service1.asmx.h:708 */
struct tfzw__executeSql_USCOREencodeResponse;	/* .\Service1.asmx.h:781 */
struct tfzw__executeSql_USCOREencode;	/* .\Service1.asmx.h:781 */
struct tfzw__insertXmlResponse;	/* .\Service1.asmx.h:857 */
struct tfzw__insertXml;	/* .\Service1.asmx.h:857 */
struct tfzw__executeStorageProcessResponse;	/* .\Service1.asmx.h:933 */
struct tfzw__executeStorageProcess;	/* .\Service1.asmx.h:933 */
struct tfzw__AddFileToSqlResponse;	/* .\Service1.asmx.h:1021 */
struct tfzw__AddFileToSql;	/* .\Service1.asmx.h:1021 */
struct tfzw__AddNumbers_Response;	/* .\Service1.asmx.h:1094 */
struct tfzw__AddNumbers_;	/* .\Service1.asmx.h:1094 */
struct tfzw__clearLink_Response;	/* .\Service1.asmx.h:1164 */
struct tfzw__clearLink_;	/* .\Service1.asmx.h:1164 */
struct tfzw__showExistLink_Response;	/* .\Service1.asmx.h:1231 */
struct tfzw__showExistLink_;	/* .\Service1.asmx.h:1231 */
struct tfzw__TestLinkSqlserver_Response;	/* .\Service1.asmx.h:1301 */
struct tfzw__TestLinkSqlserver_;	/* .\Service1.asmx.h:1301 */
struct tfzw__executeSql_Response;	/* .\Service1.asmx.h:1374 */
struct tfzw__executeSql_;	/* .\Service1.asmx.h:1374 */
struct tfzw__executeSql_USCOREbackEncord_Response;	/* .\Service1.asmx.h:1447 */
struct tfzw__executeSql_USCOREbackEncord_;	/* .\Service1.asmx.h:1447 */
struct tfzw__executeSql_USCOREencode_Response;	/* .\Service1.asmx.h:1520 */
struct tfzw__executeSql_USCOREencode_;	/* .\Service1.asmx.h:1520 */
struct tfzw__insertXml_Response;	/* .\Service1.asmx.h:1596 */
struct tfzw__insertXml_;	/* .\Service1.asmx.h:1596 */
struct tfzw__executeStorageProcess_Response;	/* .\Service1.asmx.h:1672 */
struct tfzw__executeStorageProcess_;	/* .\Service1.asmx.h:1672 */
struct tfzw__AddFileToSql_Response;	/* .\Service1.asmx.h:1760 */
struct tfzw__AddFileToSql_;	/* .\Service1.asmx.h:1760 */

/* .\Service1.asmx.h:355 */
#ifndef SOAP_TYPE_tfzw__AddNumbersResponse
#define SOAP_TYPE_tfzw__AddNumbersResponse (10)
/* complex XML schema type 'tfzw:AddNumbersResponse': */
struct SOAP_CMAC tfzw__AddNumbersResponse {
      public:
        /** Required element 'AddNumbersResult' of XML schema type 'xsd:int' */
        int AddNumbersResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddNumbersResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__AddNumbersResponse; }
        /** Constructor with member initializations */
        tfzw__AddNumbersResponse() : AddNumbersResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddNumbersResponse * SOAP_FMAC2 soap_instantiate_tfzw__AddNumbersResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:355 */
#ifndef SOAP_TYPE_tfzw__AddNumbers
#define SOAP_TYPE_tfzw__AddNumbers (11)
/* complex XML schema type 'tfzw:AddNumbers': */
struct SOAP_CMAC tfzw__AddNumbers {
      public:
        /** Required element 'NumberOne' of XML schema type 'xsd:int' */
        int NumberOne;
        /** Required element 'NumberTwo' of XML schema type 'xsd:int' */
        int NumberTwo;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddNumbers */
        long soap_type() const { return SOAP_TYPE_tfzw__AddNumbers; }
        /** Constructor with member initializations */
        tfzw__AddNumbers() : NumberOne(), NumberTwo() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddNumbers * SOAP_FMAC2 soap_instantiate_tfzw__AddNumbers(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:425 */
#ifndef SOAP_TYPE_tfzw__clearLinkResponse
#define SOAP_TYPE_tfzw__clearLinkResponse (16)
/* complex XML schema type 'tfzw:clearLinkResponse': */
struct SOAP_CMAC tfzw__clearLinkResponse {
      public:
        /** Required element 'clearLinkResult' of XML schema type 'xsd:string' */
        std::wstring clearLinkResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__clearLinkResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__clearLinkResponse; }
        /** Constructor with member initializations */
        tfzw__clearLinkResponse() : clearLinkResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__clearLinkResponse * SOAP_FMAC2 soap_instantiate_tfzw__clearLinkResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:425 */
#ifndef SOAP_TYPE_tfzw__clearLink
#define SOAP_TYPE_tfzw__clearLink (17)
/* complex XML schema type 'tfzw:clearLink': */
struct SOAP_CMAC tfzw__clearLink {
      public:
        /** Required element 'bTimeContrl' of XML schema type 'xsd:boolean' */
        bool bTimeContrl;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__clearLink */
        long soap_type() const { return SOAP_TYPE_tfzw__clearLink; }
        /** Constructor with member initializations */
        tfzw__clearLink() : bTimeContrl() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__clearLink * SOAP_FMAC2 soap_instantiate_tfzw__clearLink(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:492 */
#ifndef SOAP_TYPE_tfzw__showExistLinkResponse
#define SOAP_TYPE_tfzw__showExistLinkResponse (19)
/* complex XML schema type 'tfzw:showExistLinkResponse': */
struct SOAP_CMAC tfzw__showExistLinkResponse {
      public:
        /** Required element 'showExistLinkResult' of XML schema type 'xsd:string' */
        std::wstring showExistLinkResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__showExistLinkResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__showExistLinkResponse; }
        /** Constructor with member initializations */
        tfzw__showExistLinkResponse() : showExistLinkResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__showExistLinkResponse * SOAP_FMAC2 soap_instantiate_tfzw__showExistLinkResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:492 */
#ifndef SOAP_TYPE_tfzw__showExistLink
#define SOAP_TYPE_tfzw__showExistLink (20)
/* complex XML schema type 'tfzw:showExistLink': */
struct SOAP_CMAC tfzw__showExistLink {
      public:
        /** Return unique type id SOAP_TYPE_tfzw__showExistLink */
        long soap_type() const { return SOAP_TYPE_tfzw__showExistLink; }
        /** Constructor with member initializations */
        tfzw__showExistLink() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__showExistLink * SOAP_FMAC2 soap_instantiate_tfzw__showExistLink(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:562 */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserverResponse
#define SOAP_TYPE_tfzw__TestLinkSqlserverResponse (22)
/* complex XML schema type 'tfzw:TestLinkSqlserverResponse': */
struct SOAP_CMAC tfzw__TestLinkSqlserverResponse {
      public:
        /** Required element 'TestLinkSqlserverResult' of XML schema type 'xsd:string' */
        std::wstring TestLinkSqlserverResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__TestLinkSqlserverResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__TestLinkSqlserverResponse; }
        /** Constructor with member initializations */
        tfzw__TestLinkSqlserverResponse() : TestLinkSqlserverResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__TestLinkSqlserverResponse * SOAP_FMAC2 soap_instantiate_tfzw__TestLinkSqlserverResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:562 */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserver
#define SOAP_TYPE_tfzw__TestLinkSqlserver (23)
/* complex XML schema type 'tfzw:TestLinkSqlserver': */
struct SOAP_CMAC tfzw__TestLinkSqlserver {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__TestLinkSqlserver */
        long soap_type() const { return SOAP_TYPE_tfzw__TestLinkSqlserver; }
        /** Constructor with member initializations */
        tfzw__TestLinkSqlserver() : serverInfo() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__TestLinkSqlserver * SOAP_FMAC2 soap_instantiate_tfzw__TestLinkSqlserver(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:635 */
#ifndef SOAP_TYPE_tfzw__executeSqlResponse
#define SOAP_TYPE_tfzw__executeSqlResponse (25)
/* complex XML schema type 'tfzw:executeSqlResponse': */
struct SOAP_CMAC tfzw__executeSqlResponse {
      public:
        /** Required element 'executeSqlResult' of XML schema type 'xsd:string' */
        std::wstring executeSqlResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSqlResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSqlResponse; }
        /** Constructor with member initializations */
        tfzw__executeSqlResponse() : executeSqlResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSqlResponse * SOAP_FMAC2 soap_instantiate_tfzw__executeSqlResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:635 */
#ifndef SOAP_TYPE_tfzw__executeSql
#define SOAP_TYPE_tfzw__executeSql (26)
/* complex XML schema type 'tfzw:executeSql': */
struct SOAP_CMAC tfzw__executeSql {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'sSql' of XML schema type 'xsd:string' */
        std::wstring sSql;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql; }
        /** Constructor with member initializations */
        tfzw__executeSql() : serverInfo(), sSql() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql * SOAP_FMAC2 soap_instantiate_tfzw__executeSql(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:708 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncordResponse
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncordResponse (28)
/* complex XML schema type 'tfzw:executeSql_backEncordResponse': */
struct SOAP_CMAC tfzw__executeSql_USCOREbackEncordResponse {
      public:
        /** Required element 'executeSql_backEncordResult' of XML schema type 'xsd:string' */
        std::wstring executeSql_USCOREbackEncordResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREbackEncordResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREbackEncordResponse; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREbackEncordResponse() : executeSql_USCOREbackEncordResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREbackEncordResponse * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREbackEncordResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:708 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncord
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncord (29)
/* complex XML schema type 'tfzw:executeSql_backEncord': */
struct SOAP_CMAC tfzw__executeSql_USCOREbackEncord {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'sSql' of XML schema type 'xsd:string' */
        std::wstring sSql;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREbackEncord */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREbackEncord; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREbackEncord() : serverInfo(), sSql() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREbackEncord * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREbackEncord(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:781 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencodeResponse
#define SOAP_TYPE_tfzw__executeSql_USCOREencodeResponse (31)
/* complex XML schema type 'tfzw:executeSql_encodeResponse': */
struct SOAP_CMAC tfzw__executeSql_USCOREencodeResponse {
      public:
        /** Required element 'executeSql_encodeResult' of XML schema type 'xsd:string' */
        std::wstring executeSql_USCOREencodeResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREencodeResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREencodeResponse; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREencodeResponse() : executeSql_USCOREencodeResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREencodeResponse * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREencodeResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:781 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencode
#define SOAP_TYPE_tfzw__executeSql_USCOREencode (32)
/* complex XML schema type 'tfzw:executeSql_encode': */
struct SOAP_CMAC tfzw__executeSql_USCOREencode {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'sSql' of XML schema type 'xsd:string' */
        std::wstring sSql;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREencode */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREencode; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREencode() : serverInfo(), sSql() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREencode * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREencode(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:857 */
#ifndef SOAP_TYPE_tfzw__insertXmlResponse
#define SOAP_TYPE_tfzw__insertXmlResponse (34)
/* complex XML schema type 'tfzw:insertXmlResponse': */
struct SOAP_CMAC tfzw__insertXmlResponse {
      public:
        /** Required element 'insertXmlResult' of XML schema type 'xsd:string' */
        std::wstring insertXmlResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__insertXmlResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__insertXmlResponse; }
        /** Constructor with member initializations */
        tfzw__insertXmlResponse() : insertXmlResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__insertXmlResponse * SOAP_FMAC2 soap_instantiate_tfzw__insertXmlResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:857 */
#ifndef SOAP_TYPE_tfzw__insertXml
#define SOAP_TYPE_tfzw__insertXml (35)
/* complex XML schema type 'tfzw:insertXml': */
struct SOAP_CMAC tfzw__insertXml {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'strXml' of XML schema type 'xsd:string' */
        std::wstring strXml;
        /** Required element 'encode' of XML schema type 'xsd:boolean' */
        bool encode;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__insertXml */
        long soap_type() const { return SOAP_TYPE_tfzw__insertXml; }
        /** Constructor with member initializations */
        tfzw__insertXml() : serverInfo(), strXml(), encode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__insertXml * SOAP_FMAC2 soap_instantiate_tfzw__insertXml(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:933 */
#ifndef SOAP_TYPE_tfzw__executeStorageProcessResponse
#define SOAP_TYPE_tfzw__executeStorageProcessResponse (37)
/* complex XML schema type 'tfzw:executeStorageProcessResponse': */
struct SOAP_CMAC tfzw__executeStorageProcessResponse {
      public:
        /** Required element 'executeStorageProcessResult' of XML schema type 'xsd:string' */
        std::wstring executeStorageProcessResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeStorageProcessResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__executeStorageProcessResponse; }
        /** Constructor with member initializations */
        tfzw__executeStorageProcessResponse() : executeStorageProcessResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeStorageProcessResponse * SOAP_FMAC2 soap_instantiate_tfzw__executeStorageProcessResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:933 */
#ifndef SOAP_TYPE_tfzw__executeStorageProcess
#define SOAP_TYPE_tfzw__executeStorageProcess (38)
/* complex XML schema type 'tfzw:executeStorageProcess': */
struct SOAP_CMAC tfzw__executeStorageProcess {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'StorageProcessName' of XML schema type 'xsd:string' */
        std::wstring StorageProcessName;
        /** Required element 'Parameters' of XML schema type 'xsd:string' */
        std::wstring Parameters;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeStorageProcess */
        long soap_type() const { return SOAP_TYPE_tfzw__executeStorageProcess; }
        /** Constructor with member initializations */
        tfzw__executeStorageProcess() : serverInfo(), StorageProcessName(), Parameters() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeStorageProcess * SOAP_FMAC2 soap_instantiate_tfzw__executeStorageProcess(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1021 */
#ifndef SOAP_TYPE_tfzw__AddFileToSqlResponse
#define SOAP_TYPE_tfzw__AddFileToSqlResponse (40)
/* complex XML schema type 'tfzw:AddFileToSqlResponse': */
struct SOAP_CMAC tfzw__AddFileToSqlResponse {
      public:
        /** Required element 'AddFileToSqlResult' of XML schema type 'xsd:string' */
        std::wstring AddFileToSqlResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddFileToSqlResponse */
        long soap_type() const { return SOAP_TYPE_tfzw__AddFileToSqlResponse; }
        /** Constructor with member initializations */
        tfzw__AddFileToSqlResponse() : AddFileToSqlResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddFileToSqlResponse * SOAP_FMAC2 soap_instantiate_tfzw__AddFileToSqlResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1021 */
#ifndef SOAP_TYPE_tfzw__AddFileToSql
#define SOAP_TYPE_tfzw__AddFileToSql (41)
/* complex XML schema type 'tfzw:AddFileToSql': */
struct SOAP_CMAC tfzw__AddFileToSql {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'strFileName' of XML schema type 'xsd:string' */
        std::wstring strFileName;
        /** Required element 'sPointer' of XML schema type 'xsd:string' */
        std::wstring sPointer;
        /** Required element 'tablenamefieldname' of XML schema type 'xsd:string' */
        std::wstring tablenamefieldname;
        /** Required element 'fileIP' of XML schema type 'xsd:string' */
        std::wstring fileIP;
        /** Required element 'fileUse' of XML schema type 'xsd:string' */
        std::wstring fileUse;
        /** Required element 'filePassword' of XML schema type 'xsd:string' */
        std::wstring filePassword;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddFileToSql */
        long soap_type() const { return SOAP_TYPE_tfzw__AddFileToSql; }
        /** Constructor with member initializations */
        tfzw__AddFileToSql() : serverInfo(), strFileName(), sPointer(), tablenamefieldname(), fileIP(), fileUse(), filePassword() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddFileToSql * SOAP_FMAC2 soap_instantiate_tfzw__AddFileToSql(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1094 */
#ifndef SOAP_TYPE_tfzw__AddNumbers_Response
#define SOAP_TYPE_tfzw__AddNumbers_Response (43)
/* complex XML schema type 'tfzw:AddNumbers-Response': */
struct SOAP_CMAC tfzw__AddNumbers_Response {
      public:
        /** Required element 'AddNumbersResult' of XML schema type 'xsd:int' */
        int AddNumbersResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddNumbers_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__AddNumbers_Response; }
        /** Constructor with member initializations */
        tfzw__AddNumbers_Response() : AddNumbersResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddNumbers_Response * SOAP_FMAC2 soap_instantiate_tfzw__AddNumbers_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1094 */
#ifndef SOAP_TYPE_tfzw__AddNumbers_
#define SOAP_TYPE_tfzw__AddNumbers_ (44)
/* complex XML schema type 'tfzw:AddNumbers': */
struct SOAP_CMAC tfzw__AddNumbers_ {
      public:
        /** Required element 'NumberOne' of XML schema type 'xsd:int' */
        int NumberOne;
        /** Required element 'NumberTwo' of XML schema type 'xsd:int' */
        int NumberTwo;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddNumbers_ */
        long soap_type() const { return SOAP_TYPE_tfzw__AddNumbers_; }
        /** Constructor with member initializations */
        tfzw__AddNumbers_() : NumberOne(), NumberTwo() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddNumbers_ * SOAP_FMAC2 soap_instantiate_tfzw__AddNumbers_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1164 */
#ifndef SOAP_TYPE_tfzw__clearLink_Response
#define SOAP_TYPE_tfzw__clearLink_Response (46)
/* complex XML schema type 'tfzw:clearLink-Response': */
struct SOAP_CMAC tfzw__clearLink_Response {
      public:
        /** Required element 'clearLinkResult' of XML schema type 'xsd:string' */
        std::wstring clearLinkResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__clearLink_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__clearLink_Response; }
        /** Constructor with member initializations */
        tfzw__clearLink_Response() : clearLinkResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__clearLink_Response * SOAP_FMAC2 soap_instantiate_tfzw__clearLink_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1164 */
#ifndef SOAP_TYPE_tfzw__clearLink_
#define SOAP_TYPE_tfzw__clearLink_ (47)
/* complex XML schema type 'tfzw:clearLink': */
struct SOAP_CMAC tfzw__clearLink_ {
      public:
        /** Required element 'bTimeContrl' of XML schema type 'xsd:boolean' */
        bool bTimeContrl;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__clearLink_ */
        long soap_type() const { return SOAP_TYPE_tfzw__clearLink_; }
        /** Constructor with member initializations */
        tfzw__clearLink_() : bTimeContrl() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__clearLink_ * SOAP_FMAC2 soap_instantiate_tfzw__clearLink_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1231 */
#ifndef SOAP_TYPE_tfzw__showExistLink_Response
#define SOAP_TYPE_tfzw__showExistLink_Response (49)
/* complex XML schema type 'tfzw:showExistLink-Response': */
struct SOAP_CMAC tfzw__showExistLink_Response {
      public:
        /** Required element 'showExistLinkResult' of XML schema type 'xsd:string' */
        std::wstring showExistLinkResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__showExistLink_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__showExistLink_Response; }
        /** Constructor with member initializations */
        tfzw__showExistLink_Response() : showExistLinkResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__showExistLink_Response * SOAP_FMAC2 soap_instantiate_tfzw__showExistLink_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1231 */
#ifndef SOAP_TYPE_tfzw__showExistLink_
#define SOAP_TYPE_tfzw__showExistLink_ (50)
/* complex XML schema type 'tfzw:showExistLink': */
struct SOAP_CMAC tfzw__showExistLink_ {
      public:
        /** Return unique type id SOAP_TYPE_tfzw__showExistLink_ */
        long soap_type() const { return SOAP_TYPE_tfzw__showExistLink_; }
        /** Constructor with member initializations */
        tfzw__showExistLink_() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__showExistLink_ * SOAP_FMAC2 soap_instantiate_tfzw__showExistLink_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1301 */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserver_Response
#define SOAP_TYPE_tfzw__TestLinkSqlserver_Response (52)
/* complex XML schema type 'tfzw:TestLinkSqlserver-Response': */
struct SOAP_CMAC tfzw__TestLinkSqlserver_Response {
      public:
        /** Required element 'TestLinkSqlserverResult' of XML schema type 'xsd:string' */
        std::wstring TestLinkSqlserverResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__TestLinkSqlserver_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__TestLinkSqlserver_Response; }
        /** Constructor with member initializations */
        tfzw__TestLinkSqlserver_Response() : TestLinkSqlserverResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__TestLinkSqlserver_Response * SOAP_FMAC2 soap_instantiate_tfzw__TestLinkSqlserver_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1301 */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserver_
#define SOAP_TYPE_tfzw__TestLinkSqlserver_ (53)
/* complex XML schema type 'tfzw:TestLinkSqlserver': */
struct SOAP_CMAC tfzw__TestLinkSqlserver_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__TestLinkSqlserver_ */
        long soap_type() const { return SOAP_TYPE_tfzw__TestLinkSqlserver_; }
        /** Constructor with member initializations */
        tfzw__TestLinkSqlserver_() : serverInfo() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__TestLinkSqlserver_ * SOAP_FMAC2 soap_instantiate_tfzw__TestLinkSqlserver_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1374 */
#ifndef SOAP_TYPE_tfzw__executeSql_Response
#define SOAP_TYPE_tfzw__executeSql_Response (55)
/* complex XML schema type 'tfzw:executeSql-Response': */
struct SOAP_CMAC tfzw__executeSql_Response {
      public:
        /** Required element 'executeSqlResult' of XML schema type 'xsd:string' */
        std::wstring executeSqlResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_Response; }
        /** Constructor with member initializations */
        tfzw__executeSql_Response() : executeSqlResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_Response * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1374 */
#ifndef SOAP_TYPE_tfzw__executeSql_
#define SOAP_TYPE_tfzw__executeSql_ (56)
/* complex XML schema type 'tfzw:executeSql': */
struct SOAP_CMAC tfzw__executeSql_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'sSql' of XML schema type 'xsd:string' */
        std::wstring sSql;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_ */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_; }
        /** Constructor with member initializations */
        tfzw__executeSql_() : serverInfo(), sSql() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_ * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1447 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_Response
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_Response (58)
/* complex XML schema type 'tfzw:executeSql_backEncord-Response': */
struct SOAP_CMAC tfzw__executeSql_USCOREbackEncord_Response {
      public:
        /** Required element 'executeSql_backEncordResult' of XML schema type 'xsd:string' */
        std::wstring executeSql_USCOREbackEncordResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_Response; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREbackEncord_Response() : executeSql_USCOREbackEncordResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREbackEncord_Response * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREbackEncord_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1447 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_ (59)
/* complex XML schema type 'tfzw:executeSql_backEncord': */
struct SOAP_CMAC tfzw__executeSql_USCOREbackEncord_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'sSql' of XML schema type 'xsd:string' */
        std::wstring sSql;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_ */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREbackEncord_() : serverInfo(), sSql() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREbackEncord_ * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREbackEncord_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1520 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencode_Response
#define SOAP_TYPE_tfzw__executeSql_USCOREencode_Response (61)
/* complex XML schema type 'tfzw:executeSql_encode-Response': */
struct SOAP_CMAC tfzw__executeSql_USCOREencode_Response {
      public:
        /** Required element 'executeSql_encodeResult' of XML schema type 'xsd:string' */
        std::wstring executeSql_USCOREencodeResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREencode_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREencode_Response; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREencode_Response() : executeSql_USCOREencodeResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREencode_Response * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREencode_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1520 */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencode_
#define SOAP_TYPE_tfzw__executeSql_USCOREencode_ (62)
/* complex XML schema type 'tfzw:executeSql_encode': */
struct SOAP_CMAC tfzw__executeSql_USCOREencode_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'sSql' of XML schema type 'xsd:string' */
        std::wstring sSql;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeSql_USCOREencode_ */
        long soap_type() const { return SOAP_TYPE_tfzw__executeSql_USCOREencode_; }
        /** Constructor with member initializations */
        tfzw__executeSql_USCOREencode_() : serverInfo(), sSql() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeSql_USCOREencode_ * SOAP_FMAC2 soap_instantiate_tfzw__executeSql_USCOREencode_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1596 */
#ifndef SOAP_TYPE_tfzw__insertXml_Response
#define SOAP_TYPE_tfzw__insertXml_Response (64)
/* complex XML schema type 'tfzw:insertXml-Response': */
struct SOAP_CMAC tfzw__insertXml_Response {
      public:
        /** Required element 'insertXmlResult' of XML schema type 'xsd:string' */
        std::wstring insertXmlResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__insertXml_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__insertXml_Response; }
        /** Constructor with member initializations */
        tfzw__insertXml_Response() : insertXmlResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__insertXml_Response * SOAP_FMAC2 soap_instantiate_tfzw__insertXml_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1596 */
#ifndef SOAP_TYPE_tfzw__insertXml_
#define SOAP_TYPE_tfzw__insertXml_ (65)
/* complex XML schema type 'tfzw:insertXml': */
struct SOAP_CMAC tfzw__insertXml_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'strXml' of XML schema type 'xsd:string' */
        std::wstring strXml;
        /** Required element 'encode' of XML schema type 'xsd:boolean' */
        bool encode;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__insertXml_ */
        long soap_type() const { return SOAP_TYPE_tfzw__insertXml_; }
        /** Constructor with member initializations */
        tfzw__insertXml_() : serverInfo(), strXml(), encode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__insertXml_ * SOAP_FMAC2 soap_instantiate_tfzw__insertXml_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1672 */
#ifndef SOAP_TYPE_tfzw__executeStorageProcess_Response
#define SOAP_TYPE_tfzw__executeStorageProcess_Response (67)
/* complex XML schema type 'tfzw:executeStorageProcess-Response': */
struct SOAP_CMAC tfzw__executeStorageProcess_Response {
      public:
        /** Required element 'executeStorageProcessResult' of XML schema type 'xsd:string' */
        std::wstring executeStorageProcessResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeStorageProcess_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__executeStorageProcess_Response; }
        /** Constructor with member initializations */
        tfzw__executeStorageProcess_Response() : executeStorageProcessResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeStorageProcess_Response * SOAP_FMAC2 soap_instantiate_tfzw__executeStorageProcess_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1672 */
#ifndef SOAP_TYPE_tfzw__executeStorageProcess_
#define SOAP_TYPE_tfzw__executeStorageProcess_ (68)
/* complex XML schema type 'tfzw:executeStorageProcess': */
struct SOAP_CMAC tfzw__executeStorageProcess_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'StorageProcessName' of XML schema type 'xsd:string' */
        std::wstring StorageProcessName;
        /** Required element 'Parameters' of XML schema type 'xsd:string' */
        std::wstring Parameters;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__executeStorageProcess_ */
        long soap_type() const { return SOAP_TYPE_tfzw__executeStorageProcess_; }
        /** Constructor with member initializations */
        tfzw__executeStorageProcess_() : serverInfo(), StorageProcessName(), Parameters() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__executeStorageProcess_ * SOAP_FMAC2 soap_instantiate_tfzw__executeStorageProcess_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1760 */
#ifndef SOAP_TYPE_tfzw__AddFileToSql_Response
#define SOAP_TYPE_tfzw__AddFileToSql_Response (70)
/* complex XML schema type 'tfzw:AddFileToSql-Response': */
struct SOAP_CMAC tfzw__AddFileToSql_Response {
      public:
        /** Required element 'AddFileToSqlResult' of XML schema type 'xsd:string' */
        std::wstring AddFileToSqlResult;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddFileToSql_Response */
        long soap_type() const { return SOAP_TYPE_tfzw__AddFileToSql_Response; }
        /** Constructor with member initializations */
        tfzw__AddFileToSql_Response() : AddFileToSqlResult() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddFileToSql_Response * SOAP_FMAC2 soap_instantiate_tfzw__AddFileToSql_Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1760 */
#ifndef SOAP_TYPE_tfzw__AddFileToSql_
#define SOAP_TYPE_tfzw__AddFileToSql_ (71)
/* complex XML schema type 'tfzw:AddFileToSql': */
struct SOAP_CMAC tfzw__AddFileToSql_ {
      public:
        /** Required element 'serverInfo' of XML schema type 'xsd:string' */
        std::wstring serverInfo;
        /** Required element 'strFileName' of XML schema type 'xsd:string' */
        std::wstring strFileName;
        /** Required element 'sPointer' of XML schema type 'xsd:string' */
        std::wstring sPointer;
        /** Required element 'tablenamefieldname' of XML schema type 'xsd:string' */
        std::wstring tablenamefieldname;
        /** Required element 'fileIP' of XML schema type 'xsd:string' */
        std::wstring fileIP;
        /** Required element 'fileUse' of XML schema type 'xsd:string' */
        std::wstring fileUse;
        /** Required element 'filePassword' of XML schema type 'xsd:string' */
        std::wstring filePassword;
      public:
        /** Return unique type id SOAP_TYPE_tfzw__AddFileToSql_ */
        long soap_type() const { return SOAP_TYPE_tfzw__AddFileToSql_; }
        /** Constructor with member initializations */
        tfzw__AddFileToSql_() : serverInfo(), strFileName(), sPointer(), tablenamefieldname(), fileIP(), fileUse(), filePassword() { }
        /** Friend allocator */
        friend SOAP_FMAC1 tfzw__AddFileToSql_ * SOAP_FMAC2 soap_instantiate_tfzw__AddFileToSql_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\Service1.asmx.h:1821 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (72)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\Service1.asmx.h:1821 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (73)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\Service1.asmx.h:1821 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (75)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\Service1.asmx.h:1821 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (78)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\Service1.asmx.h:1821 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (79)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* bool has binding name 'bool' for type 'xsd:boolean' */
#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (12)
#endif

/* std::wstring has binding name 'std__wstring' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__wstring
#define SOAP_TYPE_std__wstring (13)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (79)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (78)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (75)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (73)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (72)
#endif

/* struct tfzw__AddFileToSql_ has binding name 'tfzw__AddFileToSql_' for type 'tfzw:AddFileToSql' */
#ifndef SOAP_TYPE_tfzw__AddFileToSql_
#define SOAP_TYPE_tfzw__AddFileToSql_ (71)
#endif

/* struct tfzw__AddFileToSql_Response has binding name 'tfzw__AddFileToSql_Response' for type 'tfzw:AddFileToSql-Response' */
#ifndef SOAP_TYPE_tfzw__AddFileToSql_Response
#define SOAP_TYPE_tfzw__AddFileToSql_Response (70)
#endif

/* struct tfzw__executeStorageProcess_ has binding name 'tfzw__executeStorageProcess_' for type 'tfzw:executeStorageProcess' */
#ifndef SOAP_TYPE_tfzw__executeStorageProcess_
#define SOAP_TYPE_tfzw__executeStorageProcess_ (68)
#endif

/* struct tfzw__executeStorageProcess_Response has binding name 'tfzw__executeStorageProcess_Response' for type 'tfzw:executeStorageProcess-Response' */
#ifndef SOAP_TYPE_tfzw__executeStorageProcess_Response
#define SOAP_TYPE_tfzw__executeStorageProcess_Response (67)
#endif

/* struct tfzw__insertXml_ has binding name 'tfzw__insertXml_' for type 'tfzw:insertXml' */
#ifndef SOAP_TYPE_tfzw__insertXml_
#define SOAP_TYPE_tfzw__insertXml_ (65)
#endif

/* struct tfzw__insertXml_Response has binding name 'tfzw__insertXml_Response' for type 'tfzw:insertXml-Response' */
#ifndef SOAP_TYPE_tfzw__insertXml_Response
#define SOAP_TYPE_tfzw__insertXml_Response (64)
#endif

/* struct tfzw__executeSql_USCOREencode_ has binding name 'tfzw__executeSql_USCOREencode_' for type 'tfzw:executeSql_encode' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencode_
#define SOAP_TYPE_tfzw__executeSql_USCOREencode_ (62)
#endif

/* struct tfzw__executeSql_USCOREencode_Response has binding name 'tfzw__executeSql_USCOREencode_Response' for type 'tfzw:executeSql_encode-Response' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencode_Response
#define SOAP_TYPE_tfzw__executeSql_USCOREencode_Response (61)
#endif

/* struct tfzw__executeSql_USCOREbackEncord_ has binding name 'tfzw__executeSql_USCOREbackEncord_' for type 'tfzw:executeSql_backEncord' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_ (59)
#endif

/* struct tfzw__executeSql_USCOREbackEncord_Response has binding name 'tfzw__executeSql_USCOREbackEncord_Response' for type 'tfzw:executeSql_backEncord-Response' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_Response
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncord_Response (58)
#endif

/* struct tfzw__executeSql_ has binding name 'tfzw__executeSql_' for type 'tfzw:executeSql' */
#ifndef SOAP_TYPE_tfzw__executeSql_
#define SOAP_TYPE_tfzw__executeSql_ (56)
#endif

/* struct tfzw__executeSql_Response has binding name 'tfzw__executeSql_Response' for type 'tfzw:executeSql-Response' */
#ifndef SOAP_TYPE_tfzw__executeSql_Response
#define SOAP_TYPE_tfzw__executeSql_Response (55)
#endif

/* struct tfzw__TestLinkSqlserver_ has binding name 'tfzw__TestLinkSqlserver_' for type 'tfzw:TestLinkSqlserver' */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserver_
#define SOAP_TYPE_tfzw__TestLinkSqlserver_ (53)
#endif

/* struct tfzw__TestLinkSqlserver_Response has binding name 'tfzw__TestLinkSqlserver_Response' for type 'tfzw:TestLinkSqlserver-Response' */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserver_Response
#define SOAP_TYPE_tfzw__TestLinkSqlserver_Response (52)
#endif

/* struct tfzw__showExistLink_ has binding name 'tfzw__showExistLink_' for type 'tfzw:showExistLink' */
#ifndef SOAP_TYPE_tfzw__showExistLink_
#define SOAP_TYPE_tfzw__showExistLink_ (50)
#endif

/* struct tfzw__showExistLink_Response has binding name 'tfzw__showExistLink_Response' for type 'tfzw:showExistLink-Response' */
#ifndef SOAP_TYPE_tfzw__showExistLink_Response
#define SOAP_TYPE_tfzw__showExistLink_Response (49)
#endif

/* struct tfzw__clearLink_ has binding name 'tfzw__clearLink_' for type 'tfzw:clearLink' */
#ifndef SOAP_TYPE_tfzw__clearLink_
#define SOAP_TYPE_tfzw__clearLink_ (47)
#endif

/* struct tfzw__clearLink_Response has binding name 'tfzw__clearLink_Response' for type 'tfzw:clearLink-Response' */
#ifndef SOAP_TYPE_tfzw__clearLink_Response
#define SOAP_TYPE_tfzw__clearLink_Response (46)
#endif

/* struct tfzw__AddNumbers_ has binding name 'tfzw__AddNumbers_' for type 'tfzw:AddNumbers' */
#ifndef SOAP_TYPE_tfzw__AddNumbers_
#define SOAP_TYPE_tfzw__AddNumbers_ (44)
#endif

/* struct tfzw__AddNumbers_Response has binding name 'tfzw__AddNumbers_Response' for type 'tfzw:AddNumbers-Response' */
#ifndef SOAP_TYPE_tfzw__AddNumbers_Response
#define SOAP_TYPE_tfzw__AddNumbers_Response (43)
#endif

/* struct tfzw__AddFileToSql has binding name 'tfzw__AddFileToSql' for type 'tfzw:AddFileToSql' */
#ifndef SOAP_TYPE_tfzw__AddFileToSql
#define SOAP_TYPE_tfzw__AddFileToSql (41)
#endif

/* struct tfzw__AddFileToSqlResponse has binding name 'tfzw__AddFileToSqlResponse' for type 'tfzw:AddFileToSqlResponse' */
#ifndef SOAP_TYPE_tfzw__AddFileToSqlResponse
#define SOAP_TYPE_tfzw__AddFileToSqlResponse (40)
#endif

/* struct tfzw__executeStorageProcess has binding name 'tfzw__executeStorageProcess' for type 'tfzw:executeStorageProcess' */
#ifndef SOAP_TYPE_tfzw__executeStorageProcess
#define SOAP_TYPE_tfzw__executeStorageProcess (38)
#endif

/* struct tfzw__executeStorageProcessResponse has binding name 'tfzw__executeStorageProcessResponse' for type 'tfzw:executeStorageProcessResponse' */
#ifndef SOAP_TYPE_tfzw__executeStorageProcessResponse
#define SOAP_TYPE_tfzw__executeStorageProcessResponse (37)
#endif

/* struct tfzw__insertXml has binding name 'tfzw__insertXml' for type 'tfzw:insertXml' */
#ifndef SOAP_TYPE_tfzw__insertXml
#define SOAP_TYPE_tfzw__insertXml (35)
#endif

/* struct tfzw__insertXmlResponse has binding name 'tfzw__insertXmlResponse' for type 'tfzw:insertXmlResponse' */
#ifndef SOAP_TYPE_tfzw__insertXmlResponse
#define SOAP_TYPE_tfzw__insertXmlResponse (34)
#endif

/* struct tfzw__executeSql_USCOREencode has binding name 'tfzw__executeSql_USCOREencode' for type 'tfzw:executeSql_encode' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencode
#define SOAP_TYPE_tfzw__executeSql_USCOREencode (32)
#endif

/* struct tfzw__executeSql_USCOREencodeResponse has binding name 'tfzw__executeSql_USCOREencodeResponse' for type 'tfzw:executeSql_encodeResponse' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREencodeResponse
#define SOAP_TYPE_tfzw__executeSql_USCOREencodeResponse (31)
#endif

/* struct tfzw__executeSql_USCOREbackEncord has binding name 'tfzw__executeSql_USCOREbackEncord' for type 'tfzw:executeSql_backEncord' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncord
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncord (29)
#endif

/* struct tfzw__executeSql_USCOREbackEncordResponse has binding name 'tfzw__executeSql_USCOREbackEncordResponse' for type 'tfzw:executeSql_backEncordResponse' */
#ifndef SOAP_TYPE_tfzw__executeSql_USCOREbackEncordResponse
#define SOAP_TYPE_tfzw__executeSql_USCOREbackEncordResponse (28)
#endif

/* struct tfzw__executeSql has binding name 'tfzw__executeSql' for type 'tfzw:executeSql' */
#ifndef SOAP_TYPE_tfzw__executeSql
#define SOAP_TYPE_tfzw__executeSql (26)
#endif

/* struct tfzw__executeSqlResponse has binding name 'tfzw__executeSqlResponse' for type 'tfzw:executeSqlResponse' */
#ifndef SOAP_TYPE_tfzw__executeSqlResponse
#define SOAP_TYPE_tfzw__executeSqlResponse (25)
#endif

/* struct tfzw__TestLinkSqlserver has binding name 'tfzw__TestLinkSqlserver' for type 'tfzw:TestLinkSqlserver' */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserver
#define SOAP_TYPE_tfzw__TestLinkSqlserver (23)
#endif

/* struct tfzw__TestLinkSqlserverResponse has binding name 'tfzw__TestLinkSqlserverResponse' for type 'tfzw:TestLinkSqlserverResponse' */
#ifndef SOAP_TYPE_tfzw__TestLinkSqlserverResponse
#define SOAP_TYPE_tfzw__TestLinkSqlserverResponse (22)
#endif

/* struct tfzw__showExistLink has binding name 'tfzw__showExistLink' for type 'tfzw:showExistLink' */
#ifndef SOAP_TYPE_tfzw__showExistLink
#define SOAP_TYPE_tfzw__showExistLink (20)
#endif

/* struct tfzw__showExistLinkResponse has binding name 'tfzw__showExistLinkResponse' for type 'tfzw:showExistLinkResponse' */
#ifndef SOAP_TYPE_tfzw__showExistLinkResponse
#define SOAP_TYPE_tfzw__showExistLinkResponse (19)
#endif

/* struct tfzw__clearLink has binding name 'tfzw__clearLink' for type 'tfzw:clearLink' */
#ifndef SOAP_TYPE_tfzw__clearLink
#define SOAP_TYPE_tfzw__clearLink (17)
#endif

/* struct tfzw__clearLinkResponse has binding name 'tfzw__clearLinkResponse' for type 'tfzw:clearLinkResponse' */
#ifndef SOAP_TYPE_tfzw__clearLinkResponse
#define SOAP_TYPE_tfzw__clearLinkResponse (16)
#endif

/* struct tfzw__AddNumbers has binding name 'tfzw__AddNumbers' for type 'tfzw:AddNumbers' */
#ifndef SOAP_TYPE_tfzw__AddNumbers
#define SOAP_TYPE_tfzw__AddNumbers (11)
#endif

/* struct tfzw__AddNumbersResponse has binding name 'tfzw__AddNumbersResponse' for type 'tfzw:AddNumbersResponse' */
#ifndef SOAP_TYPE_tfzw__AddNumbersResponse
#define SOAP_TYPE_tfzw__AddNumbersResponse (10)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (81)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (80)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (74)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
